# -*- coding: utf-8 -*-
"""maximizing-taxi-driver-revenue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jlzn2wyLQkAcZmbuD4SkdrNiEoE-CpJb
"""

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
# for dirname, _, filenames in os.walk('/kaggle/input'):
#     for filename in filenames:
#         print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

"""# Problem Statement

In the competitive taxi industry, optimizing revenue streams is essential for long-term success and driver satisfaction. With the advent of digital payments, understanding how payment methods impact fare pricing has become increasingly important for maximizing earnings.

Our research focuses on leveraging **data-driven insights** to determine whether there is a significant relationship between the total fare amount and payment type. By analyzing the connection between payment methods (e.g., cash versus credit cards) and fare pricing, we aim to uncover actionable strategies for increasing driver revenue.

# Objective

The primary goal of this project is to conduct a hypothesis test to examine whether the method of payment influences total fare amounts. Using Python for hypothesis testing and descriptive statistics, we aim to answer the following:
- Are customers who pay via credit cards associated with higher fare amounts compared to those paying with cash?
- Can insights from payment trends guide strategies for encouraging higher-revenue payment methods without impacting customer satisfaction?

# Research Question

**Does the method of payment have a significant impact on the total fare amount?**

By answering this question, we aim to provide practical recommendations to taxi drivers and operators on how to align payment policies with revenue optimization.

## Importing Libraries
"""

# to store and process data in dataframes
import pandas as pd
# basic visualization package
import matplotlib.pyplot as plt
# advanced ploting
import seaborn as sns
# for advanced statistics
import scipy.stats as stats
# for statistical plotting
import statsmodels.api as sm
# for regression analysis
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
# hide warnings
import warnings
warnings.filterwarnings('ignore')

# color pallette
edge, prim, sec, ter, quar, quin = '#000000', '#FA643F', '#FFBCAB', '#CBB2B2', '#F1F1F1', '#FD9F9F'

# seaborn plot style
sns.set_style('darkgrid')

"""## Loading the Dataset"""

df = pd.read_csv('/kaggle/input/newyork-yellow-taxi-trip-data-2020-2019/yellow_tripdata_2020-01.csv')

df.head()

"""## Exploratory Data Analysis

In this section, we explore the dataset to understand its structure and key attributes. The main goals of EDA are:
1. Assess the completeness and cleanliness of the dataset.
2. Analyze distributions of important features such as `trip_distance`, `fare_amount`, and `pickup_datetime`.
3. Identify patterns or anomalies that might influence revenue.
"""

# Understanding the size of data
df.shape

# Ensuring the correct datatypes for each column
df.dtypes

# Updating the dtype from object to datetime

df['tpep_pickup_datetime'] = pd.to_datetime(df['tpep_pickup_datetime'])
df['tpep_dropoff_datetime'] = pd.to_datetime(df['tpep_dropoff_datetime'])

# Verify the dtype change
df.dtypes

# Calculating duration of each trip

df['duration'] = df['tpep_dropoff_datetime'] - df['tpep_pickup_datetime']

# Reviewing the new column
df.head()

# Updating the format of new column, so the duration is in minutes

df['duration'] = df['duration'].dt.total_seconds()/60

# Verify the format change

df.head()

# Creating a focused subset based on our objective

subset_df = df[['passenger_count', 'payment_type', 'fare_amount', 'trip_distance', 'duration']]

subset_df.head()

# Checking for missing values

subset_df.isnull().sum()

# Getting percent of missing data

print((subset_df['passenger_count'].isnull().sum() / subset_df.shape[0]) * 100)
print((subset_df['payment_type'].isnull().sum() / subset_df.shape[0]) * 100)

# Since the percent of missing data is very low it won't affect our analysis and hence can be safely dropped

subset_df.dropna(axis = 0, inplace = True)

# Confirming that there is no leftover missing value

subset_df.isnull().sum()

# Converting dtypes for a few columns

subset_df['passenger_count'] = subset_df['passenger_count'].astype('int64')
subset_df['payment_type'] = subset_df['payment_type'].astype('int64')

subset_df.head()

subset_df[subset_df.duplicated()]

# We see high duplicate count as we have ignored quite a few columns from original dataset.
# These duplicate rows will not contibute anything to our analysis hence can be safely dropped.

subset_df.drop_duplicates(inplace = True)

subset_df[subset_df.duplicated()]

subset_df.shape

# Understanding the range and percent of each possible value for different columns

subset_df['passenger_count'].value_counts(normalize = True)

subset_df['payment_type'].value_counts(normalize = True)

# Based on column description of our data we only want to consider Credit card and cash payments

subset_df = subset_df[subset_df['payment_type']<3]

# Since no passenger situation is not possible and count of passengers more than 6 contirbutes very less in our data we can safely ignore those records.
subset_df = subset_df[(subset_df['passenger_count']>0) & (subset_df['passenger_count']<6)]

subset_df['passenger_count'].value_counts(normalize = True)

subset_df['payment_type'].value_counts(normalize = True)

subset_df.shape

subset_df['payment_type'].replace([1,2], ['Card', 'Cash'], inplace = True)

subset_df.head()

subset_df.describe()

# We can see some incorrect data as negative values for fare_amount, trip_distance or duration are not possible, hence need to be removed

subset_df = subset_df[subset_df['fare_amount'] > 0]
subset_df = subset_df[subset_df['trip_distance'] > 0]
subset_df = subset_df[subset_df['duration'] > 0]

subset_df.describe()

# Checking for outliers

plt.boxplot(subset_df['fare_amount'])

# Outliers can be handled either using Z score or IQR. But since the data is not normally distributed we will be using IQR

for col in ['fare_amount', 'trip_distance', 'duration']:
    q1 = subset_df[col].quantile(0.25)
    q3 = subset_df[col].quantile(0.75)
    IQR = q3 - q1

    lower_bound = q1 - 1.5*IQR
    upper_bound = q3 + 1.5*IQR

    subset_df = subset_df[(subset_df[col] >= lower_bound) & (subset_df[col] <= upper_bound)]

plt.boxplot(subset_df['fare_amount'])

# Visualizing choice of payment type based on fare amount & trip distance

plt.figure(figsize = (12,5))
plt.subplot(1,2,1)
plt.title('Distribution of Fare Amount')
plt.hist(subset_df[subset_df['payment_type'] == 'Card']['fare_amount'],
         histtype = 'barstacked', bins = 20, edgecolor = edge, color = prim, label = 'Card')
plt.hist(subset_df[subset_df['payment_type'] == 'Cash']['fare_amount'],
         histtype = 'barstacked', bins = 20, edgecolor = edge, color = sec, label = 'Cash')
plt.legend()

plt.subplot(1,2,2)
plt.title('Distribution of Trip Distance')
plt.hist(subset_df[subset_df['payment_type'] == 'Card']['trip_distance'],
         histtype = 'barstacked', bins = 20, edgecolor = edge, color = prim, label = 'Card')
plt.hist(subset_df[subset_df['payment_type'] == 'Cash']['trip_distance'],
         histtype = 'barstacked', bins = 20, edgecolor = edge, color = sec, label = 'Cash')
plt.legend()
plt.show()

subset_df.groupby('payment_type').agg({'fare_amount': ['mean', 'std'], 'trip_distance': ['mean', 'std']})

# Visualizing overall distribution of payment type

plt.title('Preference of Payment Type')
plt.pie(subset_df['payment_type'].value_counts(normalize = True), labels = subset_df['payment_type'].value_counts().index,
        startangle = 90, shadow = True, autopct = '%1.1F%%', colors = [prim, sec])

# Understanding of passenger count on payment type

passenger_count = subset_df.groupby(['payment_type', 'passenger_count'])[['passenger_count']].count()
passenger_count.rename(columns = {'passenger_count': 'count'}, inplace = True)
passenger_count.reset_index(inplace = True)
passenger_count

passenger_count['perc'] = (passenger_count['count'] / passenger_count['count'].sum())* 100
passenger_count

# Creating a new transformed dataset to eventually create a stacked bar chart based on passenger count

unique_passenger_counts = [x for x in passenger_count['passenger_count'].unique()]
columns = ['payment_type'] + unique_passenger_counts

trans_passenger_count = pd.DataFrame(columns=columns)
trans_passenger_count['payment_type'] = passenger_count['payment_type'].unique()
trans_passenger_count.iloc[0, 1:] = passenger_count.iloc[:5, -1]
trans_passenger_count.iloc[1, 1:] = passenger_count.iloc[5:, -1]
trans_passenger_count

# Visualizing impact of passenger count on payment type
fig, ax = plt.subplots(figsize = (20, 6))
trans_passenger_count.plot(x ='payment_type', kind = 'barh', stacked = True, color = [prim, sec, ter, quar, quin],
                          ax = ax, ylabel = 'Payment Type')

# Adding a title
ax.set_title('Impact of Passenger Count on Payment Type', fontsize=16)

# Adding percent text
for p in ax.patches:
    width = p.get_width()
    height = p.get_height()
    x, y = p.get_xy()
    ax.text(x + width / 2,
               y + height / 2,
               '{:.0f}%'.format(width),
               horizontalalignment = 'center',
    verticalalignment = 'center')

"""## Hypothesis Testing

**Null Hypothesis :** There is no difference in average fare between customers who use credit cards and customers who use cash.

**Alternative Hypothesis :** There is a difference in average fare between customers who use credit cards and customers who use cash.

### Which Test to Use for Comparing `payment_type` (2 Groups) and `fare_amount` (Continuous):

- **Chi-square**: Cannot be used with continuous variables like `fare_amount`.
- **ANOVA**: Can be used if there are **2 or more groups**, but for exactly **2 groups**, a **t-test** is usually preferred.
- **Z Test**: Only if the sample size is large, the population standard deviation is known, and the distribution is normal.
- **T Test**: Typically used for comparing the means of **two independent groups** (e.g., `Card` vs `Cash`) when the sample size is small and the population standard deviation is unknown.

### Conclusion:
For comparing `payment_type` (with 2 independent groups) and `fare_amount` (continuous data), though the sample size is large, `fare_amount` does not follow normal distribution hence **use a T-test**.
"""

# Checking if Fare Amount is normall distrubited

sm.qqplot(subset_df['fare_amount'], line = '45')
plt.show()

# Since the points are not aligned with the line, we can deduce that fare_amount is not normally distributed

card_sample = subset_df[subset_df['payment_type'] == 'Card']['fare_amount']
cash_sample = subset_df[subset_df['payment_type'] == 'Cash']['fare_amount']

t_stats, p_value = stats.ttest_ind(a = card_sample, b = cash_sample, equal_var = False)
print('T statistics : ', t_stats, 'p-value : ', p_value)

"""### What does this output signify?
**Result**:

The t-statistic of 169.21 is extremely high, suggesting that the means of the two groups (e.g., card_sample and cash_sample) are very different.

A p-value of 0.0 means that the probability of observing such a large difference in sample means under the null hypothesis is extremely small (effectively zero).

### Conclusion:
Statistically significant result: Since the p-value is less than the commonly used significance level of 0.05 (and even far smaller), **we reject the null hypothesis** and **conclude that there is a significant difference between the two groups being compared (i.g., Payment Type - Card and Cash groups)**.

## Performing Linear Regression

Using Python's scikit-learn library for the regression analysis based on below columns -
1. `trip_duration_minutes` (numeric, independent variable X)
2. `fare_amount` (float, dependent variable Y)
"""

df.head()

# Define Features (X) and Target (Y)

X = df[['duration']]  # Independent variable (ensure it’s a 2D array)
y = df['fare_amount']  # Dependent variable

# Creating training and test sets

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Fit the Linear Regression Model

model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions

y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

# Evaluating the model

# Mean Squared Error
train_mse = mean_squared_error(y_train, y_train_pred)
test_mse = mean_squared_error(y_test, y_test_pred)
print(f"Train MSE: {train_mse}, Test MSE: {test_mse}")

#R squared error
train_r2 = r2_score(y_train, y_train_pred)
test_r2 = r2_score(y_test, y_test_pred)
print(f"Train R²: {train_r2}, Test R²: {test_r2}")

"""### What does this output signify?
1. **MSE results**
    - The Train and Test MSE values are relatively close, suggesting that the model has similar performance on both datasets and is not overfitting or underfitting.
    - However, the values themselves are quite high, implying that the model's predictions are not very close to the actual values.

2. **R squared results**
    - the 𝑅 squared values for both Train and Test datasets are extremely low (~2% and ~1.7%), suggesting that trip duration has minimal explanatory power for predicting fare amount in your data.

### Conclusion:
1. The very low 𝑅 squared values suggest that trip duration alone is not a strong predictor of fare amount.
2. The close Train and Test MSE values indicate that the model generalizes similarly on unseen data, even though the predictions are not highly accurate.
3. Need to incorporate additional features (e.g., trip distance, passenger count) to improve the model's predictive capability.
"""

import matplotlib.pyplot as plt

plt.figure(figsize=(6, 3))
plt.scatter(X_test, y_test, color='blue', label='Actual Values')
plt.plot(X_test, y_test_pred, color='red', label='Regression Line')
plt.title('Linear Regression: Trip Duration vs. Fare Amount')
plt.xlabel('Trip Duration (minutes)')
plt.ylabel('Fare Amount ($)')
plt.legend()
plt.grid(visible=True, linestyle='--', alpha=0.6)
plt.show()

"""# Summary of Findings and Recommendations

1. **Key Factors Influencing Revenue**:
   - Longer trips generally result in higher fares but might not always optimize revenue due to increased idle time.
   - Peak hours (e.g., late evenings) see higher demand, leading to increased revenue opportunities.
   - Linear regression analysis revealed that trip duration alone has minimal impact on fare prediction, as indicated by low R squared values (~2% for training data and ~1.7% for testing data). This suggests that other factors, such as trip distance or pickup time, may have stronger predictive power.

2. **Actionable Insights**:
   - Focus on shorter, frequent trips during peak hours for optimal earnings.
   - Explore popular routes and zones (e.g., airports or downtown areas) with high trip density.
   - Consider encouraging drivers to monitor trip characteristics (e.g., distance, time of day) beyond duration to maximize revenue.

3. **Future Improvements**:
   - Add features such as trip distance, passenger count, and time of day to improve the predictive power of the model.
   - Explore transformations or feature engineering to capture non-linear relationships in the data.

"""